apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-with-steph
  labels:
    app: demo-apps
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-apps
  template:
    metadata:
      labels:
        app: demo-apps
    spec:
      containers:
        - name: demo-apps
          image: stephanieada/cno-demo-app:red
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo-apps
  name: demo-apps-service
  namespace: demo-app
spec:
  allocateLoadBalancerNodePorts: true
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster

  ports:
  - nodePort: 31396
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: demo-apps
    cno-version: main
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  rules:
    - host: myapp.demo.gocno.io
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: demo-apps-service
              port:
                number: 80
